#!/usr/bin/env bash
# haproxy
sudo apt-get update -y
sudo apt-get install haproxy -y
echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 5894-web-01 54.160.201.235:80 check
    server 5894-web-02 3.87.127.32:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
