#!/usr/bin/env bash
# haproxy
sudo apt-get update -y
sudo apt-get install haproxy -y
sudo cat << EOF >> /etc/haproxy/haproxy.cfg
frontend lb_front
        bind *:80
        default_backend lb_back

backend lb_back
        balance roundrobin
        server 5894-web-01 54.160.201.235:80 check
        server 5894-web-02 3.87.127.32:80 check
EOF
sudo service haproxy restart
