#!/usr/bin/env bash
# Updating packages
sudo apt-get update
sudo apt-get install -y nginx

touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /var/www/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart