#!/usr/bin/env bash
#install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" | sudo tee /var/www/html/index.html

echo "

 http {
    server {
        listen 80;
        index index.html;
        root /var/www/html;
    }
 }


 " | sudo tee /etc/nginx/nginx.conf



sudo service nginx restart
