#!/usr/bin/env bash
#redirect
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/umumararungu permanent;"
sudo sed -i -e "s|server_name _;|$replace|" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart