#!/usr/bin/env bash
#redirect
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

replace="server_name _;\\
    rewrite ^/redirect_me https://github.com/umumararungu/ permanent;"
sudo sed -i -e "s|server_name _;|$replace|" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-available/default

sudo service nginx restart
